### ISSUE TITLE
sql code error

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/SourceMod-Shop#3]
![image](https://user-images.githubusercontent.com/33537916/52174858-da40c400-27cc-11e9-808c-f4640a7b5aed.png)

![image](https://user-images.githubusercontent.com/33537916/52174864-e3ca2c00-27cc-11e9-9089-574d1c9e41e2.png)

**Comment by Kxnrl** [comment]
NO database selected!

**Comment by ByKyTa** [comment]
@Kxnrl and this ?
Sm 1.10.6380
//// shop-skin.sp
//
// shop-skin.sp(366) : error 017: undefined symbol "SetVariantString"
// shop-skin.sp(369) : error 017: undefined symbol "SetVariantString"
//
// 2 Errors.
//
// Compilation Time: 0.11 sec
// ----------------------------------------

**Comment by Kxnrl** [comment]
https://sm.alliedmods.net/new-api/sdktools_variant_t/SetVariantString
